// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ASMSyntaxHighlighter
{
    internal sealed partial class Vsix
    {
        public const string Id = "ASMSyntaxHighlighter.9fa3f54f-bd3c-434e-bf35-2294bc0fa3f7";
        public const string Name = "ASMSyntaxHighlighter";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
